### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by evanpurkhiser** [mjg59/python-tikteck#1]
Hi there!

I'm experimenting with using some Tikteck lights in my apartment controlled over a Raspberry Pi.

I've been playing with this code to control the light, and in general it works fine, but if I leave it alone for awhile and come back and try and change the state of the light I end up having to re-connect the device.

```
>>> t.set_state(0x00, 0xff, 0xff, 0xff)
[226, 7, 0, 104, 100, 202, 90, 240, 31, 60, 67, 5, 24, 54, 216, 67, 164, 217, 38, 15]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tikteck/__init__.py", line 153, in set_state
    self.send_packet(0xffff, 0xc1, [red, green, blue, brightness])
  File "tikteck/__init__.py", line 145, in send_packet
    response = send_packet(self.sock, 0x15, enc_packet)
  File "tikteck/__init__.py", line 70, in send_packet
    sock.send(packet)
socket.error: [Errno 110] Connection timed out
>>> t.set_state(0xff, 0x00, 0x00, 0xff)
[227, 7, 0, 243, 161, 76, 2, 212, 5, 191, 87, 11, 196, 69, 18, 227, 74, 189, 97, 74]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tikteck/__init__.py", line 153, in set_state
    self.send_packet(0xffff, 0xc1, [red, green, blue, brightness])
  File "tikteck/__init__.py", line 145, in send_packet
    response = send_packet(self.sock, 0x15, enc_packet)
  File "tikteck/__init__.py", line 70, in send_packet
    sock.send(packet)
socket.error: [Errno 107] Transport endpoint is not connected
>>> t.connect()
>>> t.set_state(0x00, 0xff, 0xff, 0xff)
[229, 7, 0, 104, 218, 172, 110, 160, 248, 185, 153, 158, 61, 14, 83, 136, 90, 73, 89, 66]
[19]
```

I haven't dived into the hci packet snooping logs (to be honest, I'm really just learning about the various protocols on top of BLE, so it's all very new to me), but perhaps there's some kind of keep alive packet sent every so often?

The official app doesn't seem to have any problem staying connected.

**Comment by mjg59** [comment]
The link should be kept alive at the protocol layer - ie, Bluez and the kernel. But it's also possible that the bulb itself choose to terminate the connection. Can you run hcidump on the Pi from connection to forced disconnect and attach that?

**Comment by evanpurkhiser** [comment]
Absolutely,

Here's the test script I'm running:

``` python
#!/usr/bin/python2

import tikteck
import itertools
import time

t = tikteck.tikteck("00:21:4d:03:07:43", "Smart Light", "xxx")
t.connect()

colors = [
    [0xFF, 0x00, 0x00, 0xFF],
    [0x00, 0xFF, 0x00, 0xFF],
    [0x00, 0x00, 0xFF, 0xFF],
    [0x00, 0x00, 0x00, 0x00],
]

for colors in itertools.cycle(colors):
    t.set_state(*colors)
    time.sleep(30)
```

[Output from `sudo hcidump | ts` and running this script here.](https://gist.github.com/EvanPurkhiser/68482f6b4cb7329658d5bb71445c4026)

(heads up, I added a small bit of additional output for the connection step, so you'll see that as the first two lines of output, in case you were confused)

It's not always consistent, if I reduce the timeout to say 10 seconds I've seen it cycle for awhile before eventually disconnecting . [Here's a case where it did cycle for awhile](https://gist.github.com/EvanPurkhiser/1288461588bba45d08112356da378b32)

I've also occasionally seen `Function not implemented` errors.

NB: I actually haven't started using a Pi yet for this, right now I'm running these tests from a [Gigabyte GB-BXi5-5200](http://www.gigabyte.us/products/product-page.aspx?pid=5323#ov).

**Comment by mjg59** [comment]
Ok, so this is a copout answer, but: can you try with the bulb and the bluetooth adapter closer to each other? The quality of built-in motherboard bluetooth antennae is often very poor, especially compared to the ones in phones.

**Comment by evanpurkhiser** [comment]
Sounds pretty reasonable. Im out of town right now, but will give it a go on Sunday. Thanks.

**Comment by mjg59** [comment]
I've had your test app running for 5 minutes or so now with no failures, so I'm afraid I'd tend in that direction.

**Comment by evanpurkhiser** [comment]
Just gave this a try with my Raspberry Pi 3.

The bluetooth hardware on the rpi-3 has no trouble staying connected. I haven't seen any errors playing with it over the past hour. I'd say this is "fixed.

For posterity, the hardware I was previously testing things on where I saw this problem was a Intel Corporation Wireless 3160.
