### ISSUE TITLE
Finding the password without Android?

### ISSUE THREAD

**Issue by acgourley** [mjg59/python-tikteck#4]
While I do have an android device in the latest version of android the TikTeck app does not successfully connect to bulbs. 

I do have an iOS device and I notice a authenticated key is visible settings for the inside that app (used to allow other devices to control the same light cluster). Is this the password that you are getting from the android logs, or is it something else? 

It's not working when I use it, but as the connection step is just hanging it could be any number of other problems, so I want to ensure i have the password correct, first.

**Comment by acgourley** [comment]
For anyone else looking: There probably isn't another way. The iOS console doesn't spit this out, and the authentication code I referred to in the post is not the per-bulb 9 digit password. If you have this problem, your best bet is to borrow an android device.

**Comment by richarddomino** [comment]
I'm wondering this also; will probably end up just borrowing an Android device, but how does the app know the password?

Both the Veho and Tikteck apps can connect with my bulbs - could it be calculated from the MAC address perhaps?
